### ISSUE TITLE
Error al terminar juego

### ISSUE THREAD

**Issue by Mad-Soft** [rhaul/Parches#1]
He probado la traducción 2.0 y a parte del grandísimo trabajo que has hecho, al finalizar el juego me muestra este mensaje.
run-time error r6003, - null pointer assign
Y con la versión 1, el juego terminaba bien.
¿A que puede ser debido?

**Comment by rhaul** [comment]
Buenas.

Imagino que hablas del civilization.
Puedes pasarme la partida para reproducir el error?

**Comment by rhaul** [comment]
> He probado la traducción 2.0 y a parte del grandísimo trabajo que has hecho, al finalizar el juego me muestra este mensaje. run-time error r6003, - null pointer assign Y con la versión 1, el juego terminaba bien. ¿A que puede ser debido?

Buenas.

Imagino que hablas del civilization.
Puedes pasarme la partida para reproducir el error?

**Comment by Mad-Soft** [comment]
Si perdón era del civilization. La partida es fácil de conseguir por tí en pocos turnos. Con los colonos que te dan en el inicio empiezas a moverte por el mapa sin contruir ciudad.... así hasta que encuentras a alguien que te vence y termina la partida.
Salen los textos de con la imágenes de los arqueólogos  y se termina el juego con ese error.
Puede ser que sea por que se ha aplicado mal la traducción. Lo hice con esta versión y sus parches.
https://www.myabandonware.com/game/sid-meier-s-civilization-1nj#download

**Comment by rhaul** [comment]
Hay 2 versiones y varios parches diferentes.
Voy a probar igualmente con alguna combinación.

**Comment by rhaul** [comment]
Efectivamente ya he podido reproducir el error pero no te preocupes, es un error controlado que no afecta al juego ya que solo aparece cuando al ser eliminado te saca al MS-DOS.

Si intentas reproducir lo mismo pero en la versión original, también te saca al MS-DOS pero sin ese mensaje de error, por tanto, no afecta para nada ni al desarrollo de la partida ni a la jugabilidad. 

Igualmente, te agradezco mucho el reporte, si encuentras algo más por pequeño que sea no dudes de reportar, también quería comentarte como nota informativa, que hay un "foro" de soporte oficial de la traducción, aunque en este no se podrá mencionar ni mostrar nada relacionado con la piratearía, pero si prefieres por aquí tampoco habría problema.

https://tradusquare.es/proyectos/sid-meiers-civilization/
(el soporte se encuentra en un banner del juego que hay en la 3º ventana que hay a la derecha)

Un saludo y gracias por el reporte

**Comment by Mad-Soft** [comment]
Gracias a ti por el interés
